[general]
import = [
    "~/.config/alacritty/themes/themes/terminal_app.toml"
]
live_config_reload = true

[window]
dimensions = { columns = 90, lines = 20}
dynamic_title = true

[font]

# Normal font style
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }  
bold = {style = "Bold"}
italic = {style = "Italic"}
bold_italic = {style = "Bold Italic"}
size = 12




[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "Q", mods = "Control|Shift", action = "Quit"}
]

